### ISSUE TITLE
Translate to Spanish game levels

### ISSUE THREAD

**Issue by Villanuevand** [GregorBiswanger/rxjs-fruits#12]
Translate to spanish all the games levels using the initial approach suggested by the author of the game. 

#### Progress
- [ ] Level 1 - subscribe - PR #26 
- [ ] Level 2 - subscribe-next - PR #27 
- [ ] Level 3 - distinct - PR #28 
- [ ] Level 4 - take - PR #30
- [ ] Level 5 - filter - PR #31
- [ ] Level 6 -  map - PR #32
- [ ] Level 7 - filter-map-take - PR #33
- [ ] Level 8 - distinctuntilchanged - PR #34 
- [ ] Level 9 - skip - PR #35 
- [ ] Level 10 - skip-take-map - PR #36 
- [ ] Level 11 -merge
- [ ] Level 12 - take-last
- [ ] Level 13 - skip-last
- [ ] Level 14 - skiplast-skip-merge
- [ ] Level 15 - zip-concatmap
- [ ] Level 16 - repeat

**Comment by Villanuevand** [comment]
@GregorBiswanger I would like to take this task.

**Comment by GregorBiswanger** [comment]
We have now got Chinese and Russian :) Now only Spanish is missing..

**Comment by Villanuevand** [comment]
I'll be working on it @GregorBiswanger..

**Comment by Villanuevand** [comment]
Hey @GregorBiswanger 
Im back!

**Comment by federicolevin** [comment]
Can I help with this?

**Comment by Villanuevand** [comment]
@federicolevin for sure... 

Would you like to translate  Level 04, 05, 06?  If you want just let me know to added  into the issue.

**Comment by federicolevin** [comment]
> @federicolevin for sure...
> 
> Would you like to translate Level 04, 05, 06? If you want just let me know to added into the issue.

Yeah! I'm in 🙂

**Comment by Villanuevand** [comment]
> > @federicolevin for sure...
> > Would you like to translate Level 04, 05, 06? If you want just let me know to added into the issue.
> 
> Yeah! I'm in 🙂

@federicolevin assigned! 

Thanks to be part of the spanish translation team!

**Comment by federicolevin** [comment]
- Level 4 - take - PR #30 
- Level 5 - filter - PR #31 
- Level 6 - map - PR #32 
- Level 7 - filter-map-take - PR #33 
- Level 8 - distinctuntilchanged - PR #34 
- Level 9 - skip - PR #35 
- Level 10 - skip-take-map - PR #36 
- Level 11 - merge - PR #37 
- Level 12 - takeLast - PR #38 
- Level 13 - skipLast - PR #39 
- Level 14 - skipLast-skip-merge - PR #40 
- Level 15 - zip-concatMap - PR #41 
- Level 16 - repeat - PR #42

**Comment by GregorBiswanger** [comment]
The new version is online... with Spanish support!

Thank you all...
